---
# tasks file for ansible-influxdb
- name: configure...
  become: yes
  become_user: root
  template: >-
    src={{item}}.j2
    dest={{influxdb_dir}}/{{item}}
    mode=0644
  with_items:
    - etc/influxdb/influxdb.conf
    - etc/default/influxdb
    - lib/influxdb/init.sh

- name: install service
  include: '{{influxdb_init|default("systemd")}}.yml'
