---
- name: configure...
  become: yes
  become_user: root
  template: >-
    src={{item}}.j2
    dest={{influxdb_dir}}/{{item}}
    mode=0644
  with_items:
    - etc/influxdb/influxdb.conf
    - usr/lib/influxdb/scripts/init.sh
    - usr/lib/influxdb/scripts/influxdb.service

- name: install service
  include: '{{influxdb_init|default("systemd")}}.yml'
