---
# tasks file for ansible-influxdb
- name: configure...
  become: yes
  become_user: root
  template: >-
    src=usr/lib/influxdb/scripts/influxdb.service.j2
    dest=/usr/lib/systemd/system/influxdb.service
    mode=0644

- name: launch influxdb
  become: yes
  become_user: root
  service: name=influxdb enabled=yes state=started
